services:
    neuron:
        build: ./
        ports:
            - 7000:7000
            - 502:502
        volumes:
            - neuron-data:/opt/neuron/persistence
            - ./logs/neuron:/opt/neuron/logs
        restart: unless-stopped
        networks:
            emqx-bridge:
                aliases:
                    - neuron.emqx.io
    emqx1:
        image: emqx/emqx:latest
        environment:
            - "EMQX_NAME=emqx"
            - "EMQX_HOST=node1.emqx.io"
            - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
            - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io]"
        networks:
            emqx-bridge:
                aliases:
                    - node1.emqx.io
        volumes:
            - emqx-data-1:/opt/emqx/data
            - ./logs/emqx1:/opt/emqx/log
        ports:
            - 1883:1883
            - 8083:8083
            - 8084:8084
            - 8883:8883
            - 18083:18083
    emqx2:
        image: emqx/emqx:latest
        environment:
            - "EMQX_NAME=emqx"
            - "EMQX_HOST=node2.emqx.io"
            - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
            - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io]"
        networks:
            emqx-bridge:
                aliases:
                    - node2.emqx.io
        volumes:
            - emqx-data-2:/opt/emqx/data
            - ./logs/emqx2:/opt/emqx/log

networks:
    emqx-bridge:
        driver: bridge
volumes:
    neuron-data:
    emqx-data-1:
    emqx-data-2:
