services:
    emqx1:
        image: emqx/emqx:latest
        environment:
            - "EMQX_NAME=emqx"
            - "EMQX_HOST=node1.emqx.io"
            - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
            - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io,emqx@node3.emqx.io]"
            - "EMQX_NODE__COOKIE=/run/secrets/EMQX_NODE__COOKIE"
        secrets:
            - EMQX_NODE__COOKIE
        hostname: node1.emqx.io
        networks:
            emqx:
                aliases:
                    - node1.emqx.io
        volumes:
            - /mnt/cephfs/emqx1/data:/opt/emqx/data
            - /mnt/cephfs/emqx1/log:/opt/emqx/log
        ports:
            - 8083:8083
            - 8084:8084
            - 18083:18083
        deploy:
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
            rollback_config:
                parallelism: 1
                delay: 10s
                failure_action: continue
        healthcheck:
            test:
                [
                    "CMD",
                    "/opt/emqx/bin/emqx",
                    "ctl",
                    "status",
                    "||",
                    "exit",
                    "1",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
    emqx2:
        image: emqx/emqx:latest
        environment:
            - "EMQX_NAME=emqx"
            - "EMQX_HOST=node2.emqx.io"
            - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
            - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io,emqx@node3.emqx.io]"
            - "EMQX_NODE__COOKIE=/run/secrets/EMQX_NODE__COOKIE"
        secrets:
            - EMQX_NODE__COOKIE
        hostname: node2.emqx.io
        networks:
            emqx:
                aliases:
                    - node2.emqx.io
        volumes:
            - /mnt/cephfs/emqx2/data:/opt/emqx/data
            - /mnt/cephfs/emqx2/log:/opt/emqx/log
        deploy:
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
            rollback_config:
                parallelism: 1
                delay: 10s
                failure_action: continue
        healthcheck:
            test:
                [
                    "CMD",
                    "/opt/emqx/bin/emqx",
                    "ctl",
                    "status",
                    "||",
                    "exit",
                    "1",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
    emqx3:
        image: emqx/emqx:latest
        environment:
            - "EMQX_NAME=emqx"
            - "EMQX_HOST=node3.emqx.io"
            - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
            - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io,emqx@node3.emqx.io]"
            - "EMQX_NODE__COOKIE=/run/secrets/EMQX_NODE__COOKIE"
        secrets:
            - EMQX_NODE__COOKIE
        hostname: node3.emqx.io
        networks:
            emqx:
                aliases:
                    - node3.emqx.io
        volumes:
            - /mnt/cephfs/emqx3/data:/opt/emqx/data
            - /mnt/cephfs/emqx3/log:/opt/emqx/log
        deploy:
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
            rollback_config:
                parallelism: 1
                delay: 10s
                failure_action: continue
        healthcheck:
            test:
                [
                    "CMD",
                    "/opt/emqx/bin/emqx",
                    "ctl",
                    "status",
                    "||",
                    "exit",
                    "1",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
secrets:
    EMQX_NODE__COOKIE:
        external: true
networks:
    emqx: #driver should be overlay and is attachable
        external: true
