services:
    traefik:
        image: "traefik:latest"
        container_name: "traefik"
        command:
            - "--log.level=info"
            - "--log.filepath=/etc/traefik/traefik.log"
            - "--api.insecure=true"
            - "--providers.swarm=true"
            - "--providers.swarm.exposedbydefault=false"
            - "--ping=true"
            - "--entryPoints.ping.address=:8082"
            - "--ping.entryPoint=ping"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entryPoints.mqtt.address=:1883"
            - "--entryPoints.mqttsecure.address=:8883"
        ports:
            - 80:80
            - 443:443
            - 8080:8080
            - 1883:1883
            - 8883:8883
        deploy:
            mode: replicated
            replicas: 3
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
            rollback_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
        healthcheck:
            test: wget --quiet --tries=1 --spider http://localhost:8082/ping || exit 1
            interval: 10s
            timeout: 25s
            retries: 5
            start_period: 10s
        networks:
            - external-proxy
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
    external-proxy: #driver should be overlay and is attachable
        external: true
